server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: file:///D:\arazeck\workspaces\java\fiapdevops-tcdmicroservices\fiapdevops-tcdmicroservices\configuration-server\src\main\resources\config