DROP TABLE IF EXISTS public.TBENTREGA;

CREATE TABLE public.TBENTREGA (
  ID        VARCHAR(2) PRIMARY KEY NOT NULL,
  UF        VARCHAR(2) NOT NULL,
  SLA       VARCHAR(3) NOT NULL);

INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('01', 'AC', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('02', 'AL', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('03', 'AP', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('04', 'AM', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('05', 'BA', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('06', 'CE', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('07', 'DF', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('08', 'ES', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('09', 'GO', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('10', 'MA', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('11', 'MT', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('12', 'MS', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('13', 'MG', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('14', 'PA', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('15', 'PB', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('16', 'PR', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('17', 'PE', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('18', 'PI', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('19', 'RJ', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('20', 'RN', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('21', 'RS', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('22', 'RO', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('23', 'RR', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('24', 'SC', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('25', 'SP', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('26', 'SE', '000');
INSERT INTO TBENTREGA (ID,  UF, SLA) VALUES ('27', 'TO', '000');
